### PR TITLE
add rake task to start a IRB session with teamsnap_rb loaded

### PR DESCRIPTION
**Pull request by semmons99**

### CODE REVIEW

**Comment by glanotte** [comment]
no pry?

**Comment by glanotte** [comment]
:+1: either way, just thought I would ask :)

**Comment by semmons99** [comment]
Better? :)


*Shane Emmons* | Director of Technology and Principal Architect
TeamSnap - The easiest way to manage your team
(810) 834-9542 | shane@teamsnap.com | What is TeamSnap?
<http://www.youtube.com/watch?v=fx0vRXYGijU>

**Comment by glanotte** [comment]
lol :shipit: :rocket: :cookie:

**Pull request merged**
