### PR TITLE
Improves error returned when server throws a 500

### PR DESCRIPTION
**Pull request by PositiveControl**
Prevents `Oj::ParseError` by skipping `Oj.load(response)` when `content-type = text/html`, instead return `TeamSnap::Error` for server errors (500).

### CODE REVIEW

**Comment by semmons99** [comment]
:rocket: :moon:

Are non application/json error possible outside of the development env? I was pretty sure all our production 500 errors were json.

**Comment by PositiveControl** [comment]
@semmons99, I believe `content-type` is what's causing: https://app.honeybadger.io/projects/1188/faults/29346773#notice-summary.  Is that a correct interpretation?

**Comment by dmccraw** [comment]
🚢  it!

**Comment by semmons99** [comment]
Sounds right, we should find out why those 500s aren't JSON at some point.
This is still cool.

On Tue, Apr 5, 2016 at 4:30 PM Mark Evans <notifications@github.com> wrote:

> @semmons99 <https://github.com/semmons99>, I believe content-type is
> what's causing:
> https://app.honeybadger.io/projects/1188/faults/29346773#notice-summary.
> Is that a correct interpretation?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/teamsnap/teamsnap_rb/pull/68#issuecomment-205976069>
>
-- 

*Shane Emmons*

CTO | (810) 834-9542

[image: TeamSnap_Logo]
What is TeamSnap? *Watch our video!* <https://youtu.be/fx0vRXYGijU>

website <https://www.teamsnap.com/> | facebook
<https://www.facebook.com/TeamSnap> | twitter <https://twitter.com/teamsnap>
 | youtube <https://www.youtube.com/user/TeamsnapHQ>

**Comment by jjmocko** [comment]
:+1: for merge - I have another PR coming as well to take us to beta5

**Pull request merged**
