### PR TITLE
allow addiitonal attributes to be defined after initial item

### PR DESCRIPTION
**Pull request by glanotte**
The problem is some attributes come back from apiv3 as nil so they aren't included in the serialized object. We need to be able to add attributes in further requests if they come back as non null.

### CODE REVIEW

**Comment by semmons99** [comment]
🚀 🌑

**Comment by jjmocko** [comment]
Some benchmarking / performance testing on this before launching it out would be a good idea. This reads as a good number of extra operations throughout a connection lifetime (we call `load_class` in Item on every object that gets instantiated).

What could make this efficient is getting the version read by teamsnap_rb to only update when necessary.

**Comment by dmccraw** [comment]
Loading 1000 items
Time elapsed 857 milliseconds - original
Time elapsed 860 milliseconds - new

Loading 5000 items
Time elapsed 3938 milliseconds - original
Time elapsed 4368 milliseconds - new

Loading 10000 items
Time elapsed 8283 milliseconds - original
Time elapsed 8876 milliseconds - new

**Comment by glanotte** [comment]
Is that with ruby 1.9? Might be worth testing both 2.2 and 1.9

**Comment by dmccraw** [comment]
@glanotte It was ruby 2.2. I will check with 1.9.

**Comment by dmccraw** [comment]
Ruby 1.9
1000 objects
Orig Time elapsed 1029 milliseconds
New Time elapsed 1147 milliseconds

5000 objects 
Orig Time elapsed 5872 milliseconds
New Time elapsed 6348 milliseconds

10000 objects
Orig Time elapsed 14252.048 milliseconds
New Time elapsed 16483.727 milliseconds

**Comment by dmccraw** [comment]
@glanotte @semmons99 @jjmocko What do you think of the metrics? Are we good to go?

**Comment by glanotte** [comment]
I say good to go

**Comment by semmons99** [comment]
+1 ship it

On Tue, Jun 7, 2016 at 5:47 PM Geoff Lanotte <notifications@github.com>
wrote:

> I say good to go
>
> On Tue, Jun 7, 2016 at 16:44 Dustin McCraw <notifications@github.com>
> wrote:
>
> > @glanotte <https://github.com/glanotte> @semmons99
> > <https://github.com/semmons99> @jjmocko <https://github.com/jjmocko>
> What
> > do you think of the metrics? Are we good to go?
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/teamsnap/teamsnap_rb/pull/75#issuecomment-224424141
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AAHNRtQPGBm8xUrMAT_v0snYJG-80fYPks5qJeYygaJpZM4Iq3xx
> >
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/teamsnap/teamsnap_rb/pull/75#issuecomment-224424981>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABsH7L01yUvyXc33T7p5Mjw6xPjdrPdks5qJeb-gaJpZM4Iq3xx>
> .
>
-- 

*Shane Emmons*

CTO | (810) 834-9542

[image: TeamSnap_Logo]
What is TeamSnap? *Watch our video!* <https://youtu.be/fx0vRXYGijU>

website <https://www.teamsnap.com/> | facebook
<https://www.facebook.com/TeamSnap> | twitter <https://twitter.com/teamsnap>
 | youtube <https://www.youtube.com/user/TeamsnapHQ>

**Pull request merged**
